### ISSUE TITLE
Fix Duration Check

### ISSUE THREAD

**Issue by gerasimou** [jrharbin-york/atlas-middleware#1]
lond duration = endTime - startTime;

if (startTime < f.getEarliestStartTime()) {
    startTime = f.getEarliestStartTime();
    endTime = startTime+duration;
}

if (endTime < f.getLatesEndTime()) {
    endTime = f.getLatesEndTime();
   startTime = endTime - duration;
}

**Comment by gerasimou** [comment]
https://github.com/jrharbin-york/atlas-middleware/blob/jmetal/middleware-java/src/atlassharedclasses/FaultInstance.java

**Comment by jrharbin-york** [comment]
constrainTimeValid fixed in FaultInstance.java 
Although it needed a greater-than test rather than less-then in the second case, otherwise it always pushes faults to the end!
