### ISSUE TITLE
Fix Mutation Operator

### ISSUE THREAD

**Issue by gerasimou** [jrharbin-york/atlas-middleware#2]
- Need to use mutation probability to check whether a fault should be mutated or not

- Make sure to operate on the input FaultInstanceSetSolution (bug here)
https://github.com/jrharbin-york/atlas-middleware/blob/jmetal/middleware-java/src/exptrunner/jmetal/FaultDataAdjustMutation.java#L114

https://github.com/jrharbin-york/atlas-middleware/blob/jmetal/middleware-java/src/exptrunner/jmetal/FaultDataAdjustMutation.java

**Comment by jrharbin-york** [comment]
Added a test of mutationProb (when not met, it chooses MutationType.NONE)
All the mutation code now operates in-place on the given FaultInstances, rather than creating new ones
