### ISSUE TITLE
Bug when duplicating existing fault

### ISSUE THREAD

**Issue by gerasimou** [jrharbin-york/atlas-middleware#4]
https://github.com/jrharbin-york/atlas-middleware/blob/jmetal/middleware-java/src/atlassharedclasses/FaultInstance.java#L39-L43

**Comment by gerasimou** [comment]
Create a new Optional instance

**Comment by jrharbin-york** [comment]
Added a function setupExtraData which creates new Optionals during FautlInstance constructors
