### ISSUE TITLE
Create new FaultInstanceSetSolution during crossover

### ISSUE THREAD

**Issue by gerasimou** [jrharbin-york/atlas-middleware#5]
The following code needs to be fixed as suggested above:
https://github.com/jrharbin-york/atlas-middleware/blob/jmetal/middleware-java/src/exptrunner/jmetal/SimpleFaultMixingCrossover.java#L37-38

**Comment by jrharbin-york** [comment]
Creating empty FaultInstanceSetSolutions during the crossover on lines 40 to 41 (just using the previous ones to set the parameters)
